import type { Metadata } from "next";
import { Inter,Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer";

const inter = Inter({
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className= {inter.className}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <ToastContainer theme="colored" position="top-center"/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
